/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as EmailConfirmedRouteImport } from './routes/email-confirmed'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViajesIndexRouteImport } from './routes/viajes.index'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ViajesDestinoRouteImport } from './routes/viajes.$destino'
import { Route as TripSlugRouteImport } from './routes/trip.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNewTripRouteImport } from './routes/_authenticated/new-trip'
import { Route as AuthenticatedInspireRouteImport } from './routes/_authenticated/inspire'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedMyTripTripIdRouteImport } from './routes/_authenticated/my-trip.$tripId'
import { Route as EmailEmailQueueProcessRouteImport } from './routes/email/email/queue/process'
import { Route as EmailEmailLifecycleRunRouteImport } from './routes/email/email/lifecycle/run'
import { Route as EmailEmailAuthWebhookRouteImport } from './routes/email/email/auth/webhook'
import { Route as EmailEmailAuthPreviewRouteImport } from './routes/email/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfirmedRoute = EmailConfirmedRouteImport.update({
  id: '/email-confirmed',
  path: '/email-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesIndexRoute = ViajesIndexRouteImport.update({
  id: '/viajes/',
  path: '/viajes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesDestinoRoute = ViajesDestinoRouteImport.update({
  id: '/viajes/$destino',
  path: '/viajes/$destino',
  getParentRoute: () => rootRouteImport,
} as any)
const TripSlugRoute = TripSlugRouteImport.update({
  id: '/trip/$slug',
  path: '/trip/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/explore/$slug',
  path: '/explore/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewTripRoute = AuthenticatedNewTripRouteImport.update({
  id: '/new-trip',
  path: '/new-trip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspireRoute = AuthenticatedInspireRouteImport.update({
  id: '/inspire',
  path: '/inspire',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTripTripIdRoute =
  AuthenticatedMyTripTripIdRouteImport.update({
    id: '/my-trip/$tripId',
    path: '/my-trip/$tripId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const EmailEmailQueueProcessRoute = EmailEmailQueueProcessRouteImport.update({
  id: '/email/email/queue/process',
  path: '/email/email/queue/process',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailEmailLifecycleRunRoute = EmailEmailLifecycleRunRouteImport.update({
  id: '/email/email/lifecycle/run',
  path: '/email/email/lifecycle/run',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailEmailAuthWebhookRoute = EmailEmailAuthWebhookRouteImport.update({
  id: '/email/email/auth/webhook',
  path: '/email/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailEmailAuthPreviewRoute = EmailEmailAuthPreviewRouteImport.update({
  id: '/email/email/auth/preview',
  path: '/email/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/email-confirmed': typeof EmailConfirmedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inspire': typeof AuthenticatedInspireRoute
  '/new-trip': typeof AuthenticatedNewTripRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/trip/$slug': typeof TripSlugRoute
  '/viajes/$destino': typeof ViajesDestinoRoute
  '/explore/': typeof ExploreIndexRoute
  '/viajes/': typeof ViajesIndexRoute
  '/my-trip/$tripId': typeof AuthenticatedMyTripTripIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/email/email/auth/preview': typeof EmailEmailAuthPreviewRoute
  '/email/email/auth/webhook': typeof EmailEmailAuthWebhookRoute
  '/email/email/lifecycle/run': typeof EmailEmailLifecycleRunRoute
  '/email/email/queue/process': typeof EmailEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/email-confirmed': typeof EmailConfirmedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inspire': typeof AuthenticatedInspireRoute
  '/new-trip': typeof AuthenticatedNewTripRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/trip/$slug': typeof TripSlugRoute
  '/viajes/$destino': typeof ViajesDestinoRoute
  '/explore': typeof ExploreIndexRoute
  '/viajes': typeof ViajesIndexRoute
  '/my-trip/$tripId': typeof AuthenticatedMyTripTripIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/email/email/auth/preview': typeof EmailEmailAuthPreviewRoute
  '/email/email/auth/webhook': typeof EmailEmailAuthWebhookRoute
  '/email/email/lifecycle/run': typeof EmailEmailLifecycleRunRoute
  '/email/email/queue/process': typeof EmailEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/demo': typeof DemoRoute
  '/email-confirmed': typeof EmailConfirmedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inspire': typeof AuthenticatedInspireRoute
  '/_authenticated/new-trip': typeof AuthenticatedNewTripRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/trip/$slug': typeof TripSlugRoute
  '/viajes/$destino': typeof ViajesDestinoRoute
  '/explore/': typeof ExploreIndexRoute
  '/viajes/': typeof ViajesIndexRoute
  '/_authenticated/my-trip/$tripId': typeof AuthenticatedMyTripTripIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/email/email/auth/preview': typeof EmailEmailAuthPreviewRoute
  '/email/email/auth/webhook': typeof EmailEmailAuthWebhookRoute
  '/email/email/lifecycle/run': typeof EmailEmailLifecycleRunRoute
  '/email/email/queue/process': typeof EmailEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/email-confirmed'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/assistant'
    | '/copilot'
    | '/dashboard'
    | '/inspire'
    | '/new-trip'
    | '/onboarding'
    | '/profile'
    | '/saved'
    | '/welcome'
    | '/api/chat'
    | '/checkout/return'
    | '/explore/$slug'
    | '/invite/$token'
    | '/trip/$slug'
    | '/viajes/$destino'
    | '/explore/'
    | '/viajes/'
    | '/my-trip/$tripId'
    | '/api/public/payments/webhook'
    | '/email/email/auth/preview'
    | '/email/email/auth/webhook'
    | '/email/email/lifecycle/run'
    | '/email/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/email-confirmed'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/assistant'
    | '/copilot'
    | '/dashboard'
    | '/inspire'
    | '/new-trip'
    | '/onboarding'
    | '/profile'
    | '/saved'
    | '/welcome'
    | '/api/chat'
    | '/checkout/return'
    | '/explore/$slug'
    | '/invite/$token'
    | '/trip/$slug'
    | '/viajes/$destino'
    | '/explore'
    | '/viajes'
    | '/my-trip/$tripId'
    | '/api/public/payments/webhook'
    | '/email/email/auth/preview'
    | '/email/email/auth/webhook'
    | '/email/email/lifecycle/run'
    | '/email/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/demo'
    | '/email-confirmed'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/assistant'
    | '/_authenticated/copilot'
    | '/_authenticated/dashboard'
    | '/_authenticated/inspire'
    | '/_authenticated/new-trip'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/saved'
    | '/_authenticated/welcome'
    | '/api/chat'
    | '/checkout/return'
    | '/explore/$slug'
    | '/invite/$token'
    | '/trip/$slug'
    | '/viajes/$destino'
    | '/explore/'
    | '/viajes/'
    | '/_authenticated/my-trip/$tripId'
    | '/api/public/payments/webhook'
    | '/email/email/auth/preview'
    | '/email/email/auth/webhook'
    | '/email/email/lifecycle/run'
    | '/email/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DemoRoute: typeof DemoRoute
  EmailConfirmedRoute: typeof EmailConfirmedRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ExploreSlugRoute: typeof ExploreSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  TripSlugRoute: typeof TripSlugRoute
  ViajesDestinoRoute: typeof ViajesDestinoRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ViajesIndexRoute: typeof ViajesIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  EmailEmailAuthPreviewRoute: typeof EmailEmailAuthPreviewRoute
  EmailEmailAuthWebhookRoute: typeof EmailEmailAuthWebhookRoute
  EmailEmailLifecycleRunRoute: typeof EmailEmailLifecycleRunRoute
  EmailEmailQueueProcessRoute: typeof EmailEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-confirmed': {
      id: '/email-confirmed'
      path: '/email-confirmed'
      fullPath: '/email-confirmed'
      preLoaderRoute: typeof EmailConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes/': {
      id: '/viajes/'
      path: '/viajes'
      fullPath: '/viajes/'
      preLoaderRoute: typeof ViajesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes/$destino': {
      id: '/viajes/$destino'
      path: '/viajes/$destino'
      fullPath: '/viajes/$destino'
      preLoaderRoute: typeof ViajesDestinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$slug': {
      id: '/trip/$slug'
      path: '/trip/$slug'
      fullPath: '/trip/$slug'
      preLoaderRoute: typeof TripSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/explore/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-trip': {
      id: '/_authenticated/new-trip'
      path: '/new-trip'
      fullPath: '/new-trip'
      preLoaderRoute: typeof AuthenticatedNewTripRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspire': {
      id: '/_authenticated/inspire'
      path: '/inspire'
      fullPath: '/inspire'
      preLoaderRoute: typeof AuthenticatedInspireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-trip/$tripId': {
      id: '/_authenticated/my-trip/$tripId'
      path: '/my-trip/$tripId'
      fullPath: '/my-trip/$tripId'
      preLoaderRoute: typeof AuthenticatedMyTripTripIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/email/email/queue/process': {
      id: '/email/email/queue/process'
      path: '/email/email/queue/process'
      fullPath: '/email/email/queue/process'
      preLoaderRoute: typeof EmailEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/email/lifecycle/run': {
      id: '/email/email/lifecycle/run'
      path: '/email/email/lifecycle/run'
      fullPath: '/email/email/lifecycle/run'
      preLoaderRoute: typeof EmailEmailLifecycleRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/email/auth/webhook': {
      id: '/email/email/auth/webhook'
      path: '/email/email/auth/webhook'
      fullPath: '/email/email/auth/webhook'
      preLoaderRoute: typeof EmailEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/email/auth/preview': {
      id: '/email/email/auth/preview'
      path: '/email/email/auth/preview'
      fullPath: '/email/email/auth/preview'
      preLoaderRoute: typeof EmailEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInspireRoute: typeof AuthenticatedInspireRoute
  AuthenticatedNewTripRoute: typeof AuthenticatedNewTripRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedMyTripTripIdRoute: typeof AuthenticatedMyTripTripIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInspireRoute: AuthenticatedInspireRoute,
  AuthenticatedNewTripRoute: AuthenticatedNewTripRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedMyTripTripIdRoute: AuthenticatedMyTripTripIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DemoRoute: DemoRoute,
  EmailConfirmedRoute: EmailConfirmedRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ExploreSlugRoute: ExploreSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  TripSlugRoute: TripSlugRoute,
  ViajesDestinoRoute: ViajesDestinoRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ViajesIndexRoute: ViajesIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  EmailEmailAuthPreviewRoute: EmailEmailAuthPreviewRoute,
  EmailEmailAuthWebhookRoute: EmailEmailAuthWebhookRoute,
  EmailEmailLifecycleRunRoute: EmailEmailLifecycleRunRoute,
  EmailEmailQueueProcessRoute: EmailEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
