ALTER TABLE public.trips
  ADD COLUMN IF NOT EXISTS hotel_name TEXT,
  ADD COLUMN IF NOT EXISTS hotel_address TEXT,
  ADD COLUMN IF NOT EXISTS hotel_lat NUMERIC,
  ADD COLUMN IF NOT EXISTS hotel_lng NUMERIC;